package com.rays.form;

import java.util.Date;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import com.rays.common.BaseDTO;
import com.rays.common.BaseForm;
import com.rays.dto.ReportDTO;

public class ReportForm extends BaseForm {

	@NotEmpty(message = "please enter report name")
	private String reportName;

	@NotNull(message = "please enter generated date")
	private Date generatedDate;

	@NotEmpty(message = "please enter generated by")
	private String generatedBy;

	@NotEmpty(message = "please enter report status")
	private String reportStatus;

	public String getReportName() {
		return reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public Date getGeneratedDate() {
		return generatedDate;
	}

	public void setGeneratedDate(Date generatedDate) {
		this.generatedDate = generatedDate;
	}

	public String getGeneratedBy() {
		return generatedBy;
	}

	public void setGeneratedBy(String generatedBy) {
		this.generatedBy = generatedBy;
	}

	public String getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}

	@Override
	public BaseDTO getDto() {

		ReportDTO dto = new ReportDTO();
		
		initDTO(dto);
		dto.setReportName(reportName);
		dto.setGeneratedDate(generatedDate);
		dto.setGeneratedBy(generatedBy);
		dto.setReportStatus(reportStatus);
		
		return dto;
	}

}
